### ISSUE TITLE
ReferenceError: arguments is not defined

### ISSUE THREAD

**Issue by youjumpiwatch** [joestelmach/lint.vim#10]
%d8 ~/.vim/bundle/lint.vim/js/jshint/jshint.js ~/.vim/bundle/lint.vim/js/jshint/options.js ~/.vim/bundle/lint.vim/js/run.js -- ./abc.js

~/.vim/bundle/lint.vim/js/run.js:1: ReferenceError: arguments is not defined

var args = arguments;
           ^
ReferenceError: arguments is not defined
    at ~/.vim/bundle/lint.vim/js/run.js:1:12

**Comment by libricoleur** [comment]
Same issue here. How could I help?

**Comment by joestelmach** [comment]
what operating system are you using?

**Comment by libricoleur** [comment]
Up-to-date Arch Linux.

**Comment by joestelmach** [comment]
did you follow this procedure while installing v8?
  https://github.com/joestelmach/lint.vim

**Comment by libricoleur** [comment]
I did not, since V8 was already installed (binary package from Arch repos) and it used to work fine with Lint.Vim. Using SVN version makes it work again, thanks. It built version 3.15.1.2, Arch's version is 3.14.0.

**Comment by youjumpiwatch** [comment]
This problem is caused by v8 itself. When d8 is compiled with library=shared, the --js-arguments option would not work. The file src/d8.cc from v8 source code implies this.
