### ISSUE TITLE
(run.js) ReferenceError: arguments is not defined

### ISSUE THREAD

**Issue by steadystatic** [joestelmach/lint.vim#14]
Hi,

Quick background on my setup: I cloned lint.vim into my .janus plugins folder, went to .vim and ran rake to get latest plugin changes. 

I have installed v8 via brew on OS X 10.8.3 and using Janus....anyway...

The plugin runs when I save a buffer but I get this error:

(run.js) ReferenceError: arguments is not defined
var args = arguments;
           ^
ReferenceError: arguments is not defined

Any ideas on how to debug this? Thanks!

**Comment by joestelmach** [comment]
Take a look at this discussion here: https://github.com/joestelmach/lint.vim/issues/10

**Comment by steadystatic** [comment]
Thank you! Sorry about that – running it via svn fixed my issue.
