### ISSUE TITLE
Command to enable / disable javascript-lint for current buffer

### ISSUE THREAD

**Issue by AndrewRayCode** [joestelmach/lint.vim#4]
Something that lets me do like `nmap <Leader>js :JSLintToggle<cr>`would be SUPER useful

**Comment by dylansm** [comment]
I agree with this request. The quickfix navigation is helpful, but at times gets in the way during quick iterations — I don't want to have to keep moving back to where I was just to stick a semicolon after a console.log, for example.

**Comment by peterfoldi** [comment]
Annoyed me too :)
ea3ebb9956fc90846e499e01be597fca9041bf44
