### ISSUE TITLE
jsl.conf

### ISSUE THREAD

**Issue by eveiga** [joestelmach/lint.vim#5]
Hello!

I would like to have the possibility of loading a custom jsl.conf without having to fork your repo just to update this line:
-  let jslint_command_options = '-conf ~/.jsl.conf -nofilelisting -nocontext -nosummary -nologo -process'

Can you please advise me on this one? If you don't have any time, I would gladly help.

Best Regards

**Comment by Raimondi** [comment]
Why don't you define that var in your vimrc?

```
let jslint_command_options = '-conf ~/.jsl.conf -nofilelisting -nocontext -nosummary -nologo -process'
```

**Comment by eveiga** [comment]
Thanks!
