### ISSUE TITLE
Disable jump to first warning/error

### ISSUE THREAD

**Issue by dhruvasagar** [joestelmach/lint.vim#9]
Hi guys,

First off thanks a lot for writing this plugin, it's quite useful and slick. Syntastic plugin has recently added support for csshint but it's quite slow so I prefer using this instead. However I find it quite disturbing and annoying that my cursor is automatically taken to the first warning / error location in the file once the check is done. It would be really nice if I could disable the cursor jump because that really breaks my flow.

**Comment by steadystatic** [comment]
I would like to second this, I love lint.vim but losing my line focus is jarring. I'd like to go visit the errors in QuickFix at my convenience. Can we add something our our .vimrc files to disable the automatic focus?

**Comment by dhruvasagar** [comment]
Unfortunately I opened this issue over 8 months ago and haven't heard anything from them :/. I guess it's time to take things in my own hands, i'll try and fix this myself. Will refer to this issue once I do to update those interested.

**Comment by joestelmach** [comment]
I apologize for the radio silence.

If you end up with a solution, please submit a pull request and I'll be sure to take a look.

**Comment by dhruvasagar** [comment]
I looked at your code after ages, now that my vimL-fu is better, I can think of many ways to improve this plugin.
Will try to get to that if I find time. In the meanwhile, i'll send you the pull request for this very simple fix :)
